# Generated by Django 6.0.4 on 2026-04-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_transaction_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
